### PR TITLE
[UPD] Update translation

### PR DESCRIPTION
**Pull request by ehdem**
Replace Team Types de bénéficaires by Type de récipendaires in fr.po

### CODE REVIEW

**Comment by bwrsandman** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:-1: not consistent with other translations

I agree there is a typo though

msgstr "Type de bénéficiaires"
https://github.com/OCA/program/pull/15/files#diff-82e0a92d12dfd9022bb6825018de2c9dR114

**Comment by bwrsandman** [comment]
@yvaucher the terms have been updated to be consistent, please update your review

**Comment by yvaucher** [comment]
@ehdem @bwrsandman Could you provide an exemple of "Beneficiary" or "Beneficiary Type"

It seems to me that "Beneficiary" != "Récipiendaire"

http://fr.wiktionary.org/wiki/r%C3%A9cipiendaire
http://www.larousse.fr/dictionnaires/francais/r%C3%A9cipiendaire/67032

vs

http://en.wiktionary.org/wiki/beneficiary

**Comment by 01Solene** [comment]
"Beneficiary" = "Récipiendaire"

You could use it in differents way.
Exemple : The beneficiary of your action could be : 1) one of your customer 2) one of your partner 3) one of your employee... so you can have different kind of "beneficiary" . So you can class them in different type via Configuration type of beneficiary.

We choose "Récipiendaire" instead of "Beneficiary" because our client want it. "Récipiendaire" means someone who receives something officially

I hope my answer helps.

**Comment by yvaucher** [comment]
@01Solene Merci pour cette réponse, je me demandais si c'était un terme usité en Belle Province. Il semblerait que je manquait juste de contexte.

@ehdem @bwrsandman Approved and merged
:+1:

**Pull request merged**
