### PR TITLE
Fixup program budget view

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by dreispt** [comment]
@bwrsandman I understand this is under heavy development, but why use PRs to OCA/program during that process? Better yet, why not do that development in a branch of your fork? In principle OCA/program should have only peer reviewed code.

**Comment by bwrsandman** [comment]
I'll admit to using this PR for travis and to check the coverage percentage.
I can't really do that in my own fork. :S

**Comment by dreispt** [comment]
I see, but you can! Here is an example: https://github.com/OCA/department/pull/7

Try registering your fork on TravisCI, like I tried with this one: https://travis-ci.org/dreispt/department
I believe it will test any commit you push, even if you don't make a PR.

**Comment by bwrsandman** [comment]
Yes but, unfortunately, coverage will not take your files into consideration due to the include line being `OCA/program` and my repo would be `bwrsandman/program`.

using `program` is far too generic, I don't have a good compromise yet

**Pull request merged**
